bandapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'bandlist/', views.bandlist, name='bandlist'),
    url(r'^banddetail/(?P<id>\d+)/$', views.banddetail, name='banddetail'),
    url(r'^protected/$', views.protected_view, name='protected'),
    url(r'accounts/login/$', views.message, name='login_error'),
    # url(r'accounts/login/$', django.contrib.auth.views.login),
]

core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^book/', views.book, name='book'),
    url(r'^genre/', views.genre, name='genre'),
    url(r'^tabela/', views.tabela, name='tabela'),
    url(r'^person/', views.person, name='person'),
    url(r'^group/', views.group, name='group'),
    url(r'^membership/', views.membership, name='membership'),
    url(r'^band_listing/', views.band_listing, name='band_listing'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('core.urls')),
    url(r'^bandapp/', include(('bandapp.urls', 'bandapp'), namespace='bandapp')),
    url(r'^admin/', admin.site.urls),
]

core/models.py
from django.db import models

# Create your models here.


class Genre(models.Model):
    name = models.CharField('Nome', max_length=100)

    class Meta:
        verbose_name = 'Genre'
        verbose_name_plural = 'Genres'
        ordering = ['name']

    def __str__(self):
        return self.name


class Book(models.Model):

    name = models.CharField('Nome', max_length=100)
    genre = models.ManyToManyField(Genre)
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Book'
        verbose_name_plural = 'Books'
        ordering = ['name']

    def __str__(self):
        return self.name


class Person(models.Model):
    name = models.CharField('Pessoa', max_length=50)

    class Meta:
        verbose_name = 'Pessoa'
        verbose_name_plural = 'Pessoas'
        ordering = ['name']

    def __str__(self):
        return self.name


class Group(models.Model):
    name = models.CharField('Grupo', max_length=128)
    members = models.ManyToManyField(
        Person,
        through='Membership',
        through_fields=('group', 'person'),
    )

    class Meta:
        verbose_name = 'Grupo'
        verbose_name_plural = 'Grupos'
        ordering = ['name']

    def __str__(self):
        return self.name


class Membership(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    inviter = models.ForeignKey(
        Person,
        on_delete=models.CASCADE,
        related_name="membership_invites",
    )
    invite_reason = models.CharField(max_length=64)

    class Meta:
        verbose_name = 'Membro'
        verbose_name_plural = 'Membros'
        ordering = ['group']

    def __str__(self):
        return self.group


class Band(models.Model):

    """A model of a rock band."""
    name = models.CharField(max_length=200)
    can_rock = models.BooleanField(default=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'band'
        verbose_name_plural = 'bands'

    def __str__(self):
        return self.name

    # count members by band
    def get_members_count(self):
        return self.band.count()

    def get_band_detail_url(self):
        return u"/bands/%i" % self.id


class Member(models.Model):

    """A model of a rock band member."""
    name = models.CharField("Member's name", max_length=200)
    instrument = models.CharField(choices=(
        ('g', "Guitar"),
        ('b', "Bass"),
        ('d', "Drums"),
        ('v', "Vocal"),
        ('p', "Piano"),
    ),
        max_length=1
    )

    band = models.ForeignKey("Band",on_delete=models.PROTECT, related_name='band')

    class Meta:
        ordering = ['name']
        verbose_name = 'member'
        verbose_name_plural = 'members'

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from . models import Book, Genre, Person, Group, Membership


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('name', 'genre',)


class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ('name',)


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ('name',)


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('name', 'members',)


class MembershipForm(forms.ModelForm):
    class Meta:
        model = Membership
        fields = ('group', 'person', 'inviter', 'invite_reason',)

core/views.py
from django.shortcuts import render, redirect
from . forms import BookForm
from . forms import GenreForm
from . forms import PersonForm
from . forms import GroupForm
from . forms import MembershipForm
from . models import Band

# Create your views here.


def base(request):
    return render(request, 'core/base.html')


def home(request):
    return render(request, 'core/home.html')


def tabela(request):
    return render(request, 'core/tabela.html')


def book(request):
    if request.POST:
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('book')
    else:
        form = BookForm()
    return render(request, 'core/book.html', {'form': form})


def genre(request):
    if request.POST:
        form = GenreForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('genre')
    else:
        form = GenreForm()
    return render(request, 'core/genre.html', {'form': form})


def person(request):
    if request.POST:
        form = PersonForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('person')
    else:
        form = PersonForm()
    return render(request, 'core/person.html', {'form': form})


def group(request):
    if request.POST:
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('group')
    else:
        form = GroupForm()
    return render(request, 'core/group.html', {'form': form})


def membership(request):
    if request.POST:
        form = MembershipForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('membership')
    else:
        form = MembershipForm()
    return render(request, 'core/membership.html', {'form': form})


def band_listing(request):
    """ A view of all bands. """
    bands = Band.objects.all()
    var_get_search = request.GET.get('search_box')
    if var_get_search is not None:
        bands = bands.filter(name__icontains=var_get_search)
    return render(request, 'core/band_listing.html', {'bands': bands})

core/templates/core/snippets/cosmo.html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/cosmo/bootstrap.css" integrity="sha256-M78YHEyJaWApxrCFxVLtKiri64kQlFemS7xqyk4JoHI=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/cosmo/bootstrap.min.css" integrity="sha256-GamwdmSkzX/X39UCQREOQHmmuU2ewsnrft1flUimjxA=" crossorigin="anonymous" />

core/templates/core/snippets/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

core/templates/core/snippets/flatly.html
<!-- https://cdnjs.com/libraries/bootswatch -->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/flatly/bootstrap.css" integrity="sha256-r44RzirzXTcabq3NCtBvP+60SlyrDQ1unHZR8MuRjL8=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/flatly/bootstrap.min.css" integrity="sha256-r1WijW/SNMgOwk5LDk7QRHr6oVYYbYWMw/1kOXfYJfg=" crossorigin="anonymous" />

core/templates/core/snippets/footer.html
<footer>
  <div class="row">
    <div class="col-lg-12">
      <ul class="list-inline">
        <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
        <li><a href="{% url 'home' %}">Início</a></li>
        <li><a href="">Produtos</a></li>
        <li><a href="">Contato</a></li>
        <li><a href="">Termos e Privacidade</a></li>
      </ul>
    </div>
  </div>
</footer>

core/templates/core/snippets/js.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

core/templates/core/snippets/navbar.html
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a href="{% url 'home' %}" class="navbar-brand">Django Protótipo</a>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <li>
          <a href="{% url 'home' %}">Início</a>
        </li>
        <li>
          <a href="{% url 'tabela' %}">Tabela</a>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="mybandapp_id">Bandapp<span class="caret"></span></a>
          <ul class="dropdown-menu" aria-labelledby="mybandapp_id">
            <li><a href="{% url 'bandapp:home' %}">Band Home</a></li>
            <li><a href="{% url 'bandapp:bandlist' %}">Band List</a></li>
            <li><a href="{% url 'bandapp:protected' %}">Protected</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="download">Cadastro<span class="caret"></span></a>
          <ul class="dropdown-menu" aria-labelledby="download">
            <li><a href="{% url 'book' %}">Book</a></li>
            <li><a href="{% url 'genre' %}">Gênero</a></li>
            <li><a href="{% url 'person' %}">Person</a></li>
            <li><a href="{% url 'group' %}">Group</a></li>
            <li><a href="{% url 'membership' %}">Membership</a></li>
            <li><a href="{% url 'band_listing' %}">Lista das Bandas</a></li>
            <li><a href="">List</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="download">Categorias <span class="caret"></span></a>
          <ul class="dropdown-menu" aria-labelledby="download">
            <li><a href="">Notebooks</a></li>
            <li><a href="">Acessórios</a></li>
            <li><a href="">Celulares</a></li>
          </ul>
        </li>
        <li>
          <a href="contact.html">Contato</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Minha Conta</a></li>
      </ul>
    </div>
  </div>
</div>

core/templates/core/snippets/simplex.html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/simplex/bootstrap.css" integrity="sha256-18wbxfYromRs+3PEqAKCsib1bqp+qK7t4DNTtOHYBBY=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/simplex/bootstrap.min.css" integrity="sha256-TKhQCpupjJ8Jh7dgjeNgBsEPk1eai3l57eH/w4h48ys=" crossorigin="anonymous" />

core/templates/core/snippets/united.html
<!-- https://cdnjs.com/libraries/bootswatch -->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/united/bootstrap.css" integrity="sha256-iqQy27uuw0BmT7dOgsDx2xSBk83X5OjcOGw+WeLPCqE=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/superhero/bootstrap.min.css" integrity="sha256-LEplvgQTKatd65f2Z/JThrYx/sdoKygi0dsC1h5sInE=" crossorigin="anonymous" />